beverly_shores = []

burns_harbor = [
    "Subway",
    "McDonald's",
    "Popeyes Louisiana Kitchen",
    "Dairy Queen Grill & Chill",
    "Taco Bell",
    "Pizza Hut Express",
    "Dunkin'",
    "Domino's Pizza",
]

cedar_lake = [
    "Subway",
    "Dairy Queen Grill & Chill",
    "Dunkin'",
    "McDonald's",
    "Pizza Hut",
    "Pop's Italian Beef and Sausage",
    "Burger King",
    "Domino's Pizza",
    "Taco Bell",
]

chesterton = [
    "Subway",
    "Little Caesars Pizza",
    "Papa Johns Pizza",
    "Wendy's",
    "Dairy Queen Grill & Chill",
    "Popeyes Louisiana Kitchen",
    "Taco Bell",
    "Pizza Hut",
    "Burger King",
    "McDonald's",
    "Dunkin'",
    "Port Drive In",
    "Arby's",
    "Domino's Pizza",
    "Smoothie King",
]

dyer = [
    "Subway",
    "Pizza Hut",
    "Wendy's",
    "Five Guys",
    "Jimmy John's",
    "Dunkin'",
    "Circle K",
    "Popeyes Louisiana Kitchen",
    "Dairy Queen Grill & Chill",
    "Buffalo Wild Wings",
    "McDonald's",
    "Penn Station East Coast Subs",
    "Sharks Fish & Chicken",
    "Tacos & Burritos Rancho Grande",
    "Starbucks",
    "Pop's Beef",
]

east_chicago = [
    "Subway",
    "Little Caesars Pizza",
    "McDonald's",
    "Dunkin'",
    "Zel's Roast Beef",
    "White Castle",
    "Burger King",
    "Pizza Hut",
    "Shark's",
    "Toni's Pizza",
    "Sharks of East Chicago",
    "Wendy's",
    "Taco Delight",
    "Family pizza and bbq",
    "Taco Bell",
    "Hunt Brothers Pizza",
    "Bob's Shrimp",
]

gary = [
    "Little Caesars Pizza",
    "Rally's",
    "Exxon Gas Station( Krispy Krunchy Chicken)",
    "Taco Bell",
    "Pizza Hut Express",
    "McDonald's",
    "Harold's Chicken Shack",
    "White Castle",
    "KFC",
    "Shark's Fish & Chicken on 5th across from the school",
    "Shark's Fish & Chicken 511Vermont st",
    "Church's Texas Chicken",
    "Sharks Fish and Chicken",
    "Church Chicken",
    "Roosta's Wings, Fish & More & Grocery Store Marketplace",
    "Kings Wings & Things East Side NOT THE BROADWAY LOCATION",
    "Shrimpies Seafood N Chicken",
    "SteelCity CheeseSteaks",
    "Jerk2Go",
    "Samia Pizza",
    "Buzz Box Chicago Style Polishes & Burgers",
    "Charlie's Coney Island",
    "Tommy's Philly Steak",
    "Ruby's Fish & Chicken",
    "Sharks Fish and Chicken",
    "Vienna Hot Dogs & Snacks",
    "Tony's Ribs Fish & Chicken",
    "Sharks Fish & Chicken",
    "Big Back Shacq",
]

griffith = [
    "Subway",
    "Jimmy John's",
    "Pizza Hut",
    "Wendy's",
    "Burger King",
    "Dunkin'",
    "Orange Julius",
    "Dairy Queen Grill & Chill",
    "Chipotle Mexican Grill",
    "Taco Bell",
    "Wingstop",
    "Little Caesars Pizza",
    "Jersey Mike's Subs",
    "Ben's Soft Pretzels",
    "Panera Bread",
    "JJ Fish & Chicken",
    "Pizza Hut Express",
    "Popeyes Louisiana Kitchen",
    "Panda Express",
    "Capri's Pizza",
    "Steak 'n Shake",
    "Sharxs Fish & Chicken",
    "Red Mango",
    "Marco's Pizza",
    "Potbelly",
    "McDonald's",
    "Steak Burrito",
]

hammond = [
    "Subway",
    "Papa Johns Pizza",
    "Jimmy John's",
    "Mr. Submarine",
    "Pizza Hut",
    "Little Caesars Pizza",
    "Chipotle Mexican Grill",
    "Taco Bell",
    "Wendy's",
    "Dairy Queen Grill & Chill",
    "Buffalo Wild Wings",
    "Columbia Gyros",
    "Big Frank's Sausage",
    "Jodi's Italian Ice Factory-Hammond",
    "Circle K",
    "Starbucks",
    "Shrimp Shack",
    "Dunkin'",
    "Einstein Bros. Bagels",
    "KFC",
    "Mancino's Pizza & Grinders",
    "Culver’s",
    "Arnie's Dog House",
    "Tacos El Güero",
    "Potbelly",
]

hebron = [
    "Subway",
    "Family Express",
    "Dairy Queen Grill & Chill",
    "Hebron Lanes",
    "Cravin's To Order",
]

highland = [
    "Subway",
    "Jimmy John's",
    "Papa Johns Pizza",
    "Pizza Hut",
    "Dunkin'",
    "Wendy's",
    "Burger King",
    "Dairy Queen Grill & Chill",
    "Ben's Soft Pretzels",
    "Chipotle Mexican Grill",
    "Wingstop",
    "Little Caesars Pizza",
    "Taco Bell",
    "Jersey Mike's Subs",
    "Pizza Hut Express",
    "Einstein Bros. Bagels",
]


hobart = [
    "Fat Guys Fries INC",
    "Subway",
    "Taco Bell",
    "Papa Johns Pizza",
    "McDonald's",
    "Dunkin'",
    "Pizza Hut",
    "Marco's Pizza",
    "Long John Silver's",
    "Lincoln Carry Outs",
    "Burger King",
    "Jimmy John's",
    "Dairy Queen Grill & Chill",
    "Little Caesars Pizza",
    "KFC",
    "Philly Steak & Lemonade",
    "White Castle",
    "Domino's Pizza",
    "George's Gyros Spot 2",
    "Wingstop",
    "Arby's",
    "Shrimps Fish & Chicken",
]

kouts = ["Family Express", "Subway", "Cravin's To Order"]

lake_station = [
    "J & J's Pizza Shack",
    "Johnson's Fish & Shrimp",
    "Subway",
    "Long John Silver's",
    "Taco Bell",
    "Dunkin'",
    "Popeyes Louisiana Kitchen",
    "McDonald's",
    "Pizza Hut",
    "White Castle",
    "Burger King",
    "Jimmy John's",
    "KFC",
    "Wendy's",
    "Philly Steak & Lemonade",
    "Little Caesars Pizza",
    "Arby's",
    "Wingstop",
]

lowell = [
    "Subway",
    "Pizza Hut",
    "Burger King",
    "McDonald's",
    "Loven Oven Pizzeria",
    "KFC",
    "Dicky's Dogs",
    "Cravin's To Order",
    "Dunkin'",
    "Domino's Pizza",
    "Taco Bell",
]

merrillville = [
    "Little Caesars Pizza",
    "Subway",
    "Portillo's Merrillville",
    "Buffalo Wild Wings",
    "Papa Johns Pizza",
    "Panda Express",
    "Wendy's",
    "Panera Bread",
    "Jimmy John's",
    "Sbarro",
    "Costco Food Court",
    "Smoothie King",
    "Popeyes Louisiana Kitchen",
    "Ben's Soft Pretzels",
    "Pizza Hut",
    "Charleys Cheesesteaks",
    "Taco Bell",
    "Dunkin'",
    "McDonald's",
    "Culver’s",
    "Chick-fil-A",
    "Chipotle Mexican Grill",
]

munster = [
    "Subway",
    "Jimmy John's",
    "Pizza Hut",
    "Portillo's Merrillville",
    "Buffalo Wild Wings",
    "Papa Johns Pizza",
    "Panda Express",
    "Wendy's",
    "Panera Bread",
    "Chipotle Mexican Grill",
    "Dunkin'",
    "Little Caesars Pizza",
    "Culver’s",
    "KFC",
    "Taco Bell",
    "Ben's Soft Pretzels",
    "Starbucks",
    "Einstein Bros. Bagels",
    "Boz Hot Dogs",
    "Circle K",
]

ogden_dunes = [
    "McDonald's",
    "Starbucks",
    "Taco Bell",
    "Dairy Queen Grill & Chill",
    "Subway",
    "Depot Hot Dogs",
    "Cravin's To Order",
    "Dunkin'",
    "Domino's Pizza",
]

portage = [
    "Little Caesars Pizza",
    "Subway",
    "McDonald's",
    "Dunkin'",
    "Chipotle Mexican Grill",
    "Domino's Pizza",
    "Five Guys",
    "Panera Bread",
    "Taco Bell",
    "Dairy Queen Grill & Chill",
    "Santini's Pizza And Wings",
    "Pizza Hut",
    "Culver’s",
    "Arby's",
    "KFC",
    "Burger King",
    "Jimmy John's",
    "Wendy's",
    "Panda Express",
    "Firehouse Subs Portage",
]

porter = [
    "Subway",
    "Little Caesars Pizza",
    "Papa Johns Pizza",
    "Wendy's",
    "Dairy Queen Grill & Chill",
    "Popeyes Louisiana Kitchen",
    "Jimmy John's",
    "Taco Bell",
    "Port Drive In",
    "Pizza Hut",
    "Burger King",
    "McDonald's",
    "Dunkin'",
    "The Original George's Gyros Spot",
    "Arby's",
    "Noble Roman's Pizza",
    "Pizza Hut Express" "Smoothie King",
]

st_john = [
    "Subway",
    "Pizza Hut",
    "Dairy Queen Grill & Chill",
    "McDonald's",
    "Rosati's Pizza",
    "Jimmy John's",
    "Five Guys",
    "Popeyes Louisiana Kitchen",
    "Dunkin'",
    "Culver’s",
    "Beggar's Pizza",
    "Domino's Pizza",
    "Taco Bell",
    "Arby's",
]

schererville = [
    "Subway",
    "Pizza Hut",
    "Five Guys",
    "Domino's Pizza",
    "Papa Johns Pizza",
    "Dairy Queen Grill & Chill",
    "Popeyes Louisiana Kitchen",
    "Jimmy John's",
    "Buffalo Wild Wings",
    "Culver’s",
    "McDonald's",
    "Wendy's",
    "Rosati's Pizza",
    "Penn Station East Coast Subs",
    "Panera Bread",
    "Steak 'n Shake",
    "State Line Pizza Schererville",
]

south_haven = [
    "Subway",
    "Little Caesars Pizza",
    "Dunkin'",
    "Santini's Pizza And Wings",
    "McDonald's",
    "Firehouse Subs Portage",
    "Buffalo Wild Wings",
    "Chipotle Mexican Grill",
    "Five Guys",
    "Domino's Pizza",
    "Panera Bread",
    "Pizza Hut",
    "Taco Bell",
    "Arby's",
    "KFC",
    "Culver’s",
    "Steak 'n Shake",
    "Wendy's",
    "Ben's Soft Pretzels",
    "3 Greeks Gyros",
    "J & J's Pizza Shack",
    "Panda Express",
]

valparaiso = [
    "Subway",
    "Little Caesars Pizza",
    "Buffalo Wild Wings",
    "Inman's Bowling & Recreation Center",
    "Subway",
    "Taco Bell",
    "Pizza Hut Express",
    "Jimmy John's",
    "Subway",
    "Dunkin'",
    "Ben's Soft Pretzels",
    "Dairy Queen Grill & Chill",
    "Papa Johns Pizza",
    "Dunkin'",
    "Five Guys",
    "Panda Express",
    "Hungry Howie's Pizza",
    "J&J's Pizza Shack",
]


whiting = [
    "Subway",
    "Little Caesars Pizza",
    "McDonald's",
    "Dunkin'",
    "Popeyes Louisiana Kitchen",
    "Ben's Soft Pretzels",
    "Burger King",
    "Wendy's",
    "White Castle",
    "Capri's Pizza Of Whiting",
    "Taco Bell",
    "Waldo Cooneys Pizza",
    "Tom Strom's Pizza Setups",
    "Dairy Queen Grill & Chill",
    "Wingstop",
    "KFC",
]


all_cities_combined = set(
    beverly_shores
    + burns_harbor
    + cedar_lake
    + chesterton
    + dyer
    + east_chicago
    + gary
    + griffith
    + hammond
    + hebron
    + highland
    + hobart
    + kouts
    + lake_station
    + lowell
    + merrillville
    + munster
    + ogden_dunes
    + portage
    + porter
    + st_john
    + schererville
    + south_haven
    + valparaiso
    + whiting
)

FAST_FOOD_LIST = [
    "3 Greeks Gyros",
    "Arby's",
    "Arnie's Dog House",
    "Beggar's Pizza",
    "Ben's Soft Pretzels",
    "Big Back Shacq",
    "Big Frank's Sausage",
    "Bob's Shrimp",
    "Boz Hot Dogs",
    "Buffalo Wild Wings",
    "Burger King",
    "Buzz Box Chicago Style Polishes & Burgers",
    "Capri's Pizza",
    "Capri's Pizza Of Whiting",
    "Charleys Cheesesteaks",
    "Charlie's Coney Island",
    "Chick-fil-A",
    "Chipotle Mexican Grill",
    "Church Chicken",
    "Church's Texas Chicken",
    "Circle K",
    "Columbia Gyros",
    "Costco Food Court",
    "Cravin's To Order",
    "Culver’s",
    "Dairy Queen Grill & Chill",
    "Depot Hot Dogs",
    "Dicky's Dogs",
    "Domino's Pizza",
    "Dunkin'",
    "Einstein Bros. Bagels",
    "Exxon Gas Station( Krispy Krunchy Chicken)",
    "Family Express",
    "Family pizza and bbq",
    "Fat Guys Fries INC",
    "Firehouse Subs Portage",
    "Five Guys",
    "George's Gyros Spot 2",
    "Harold's Chicken Shack",
    "Hebron Lanes",
    "Hungry Howie's Pizza",
    "Hunt Brothers Pizza",
    "Inman's Bowling & Recreation Center",
    "J & J's Pizza Shack",
    "J&J's Pizza Shack",
    "JJ Fish & Chicken",
    "Jerk2Go",
    "Jersey Mike's Subs",
    "Jimmy John's",
    "Jodi's Italian Ice Factory-Hammond",
    "Johnson's Fish & Shrimp",
    "KFC",
    "Kings Wings & Things East Side NOT THE BROADWAY LOCATION",
    "Lincoln Carry Outs",
    "Little Caesars Pizza",
    "Long John Silver's",
    "Loven Oven Pizzeria",
    "Mancino's Pizza & Grinders",
    "Marco's Pizza",
    "McDonald's",
    "Mr. Submarine",
    "Noble Roman's Pizza",
    "Orange Julius",
    "Panda Express",
    "Panera Bread",
    "Papa Johns Pizza",
    "Penn Station East Coast Subs",
    "Philly Steak & Lemonade",
    "Pizza Hut",
    "Pizza Hut Express",
    "Pizza Hut ExpressSmoothie King",
    "Pop's Beef",
    "Pop's Italian Beef and Sausage",
    "Popeyes Louisiana Kitchen",
    "Port Drive In",
    "Portillo's Merrillville",
    "Potbelly",
    "Rally's",
    "Red Mango",
    "Roosta's Wings, Fish & More & Grocery Store Marketplace",
    "Rosati's Pizza",
    "Ruby's Fish & Chicken",
    "Samia Pizza",
    "Santini's Pizza And Wings",
    "Sbarro",
    "Shark's",
    "Shark's Fish & Chicken 511Vermont st",
    "Shark's Fish & Chicken on 5th across from the school",
    "Sharks Fish & Chicken",
    "Sharks Fish and Chicken",
    "Sharks of East Chicago",
    "Sharxs Fish & Chicken",
    "Shrimp Shack",
    "Shrimpies Seafood N Chicken",
    "Shrimps Fish & Chicken",
    "Smoothie King",
    "Starbucks",
    "State Line Pizza Schererville",
    "Steak 'n Shake",
    "Steak Burrito",
    "SteelCity CheeseSteaks",
    "Subway",
    "Taco Bell",
    "Taco Delight",
    "The Original George's Gyros Spot",
    "Tom Strom's Pizza Setups",
    "Tommy's Philly Steak",
    "Toni's Pizza",
    "Tony's Ribs Fish & Chicken",
    "Vienna Hot Dogs & Snacks",
    "Waldo Cooneys Pizza",
    "Wendy's",
    "White Castle",
    "Wingstop",
    "Zel's Roast Beef",
]
